### ISSUE TITLE
Where is "extracted_data"?

### ISSUE THREAD

**Issue by zhayert** [BASHLab/LLaSA#2]
Hello.
Thank you for provide this repository.
But where is directory named "extracted_data" ?

**Comment by shouborno** [comment]
> Hello. Thank you for provide this repository. But where is directory named "extracted_data" ?

You can follow this to prepare the extracted_data folder for HHAR, MotionSense, UCI HAR, and Shoaib et al. HAR datasets: https://github.com/dapowan/LIMU-BERT-Public/tree/master/dataset
