### ISSUE TITLE
LIMU-BERT Training Details.

### ISSUE THREAD

**Issue by xiaokj37** [BASHLab/LLaSA#3]
Thanks to the author for open-sourcing the work.
I would like to ask about LIMU-BERT Training Details. 
In the pre-training script, the vision tower comes from ‘--vision_tower /home/simran/model.pt \’. 
LIMU-BERT was retrained as described in the paper, and I would like to know, what is this ‘model.pt’?

**Comment by shouborno** [comment]
Once we train LIMU-BERT following https://github.com/dapowan/LIMU-BERT-Public , we get a `model.pt` file, which can be plugged in here to encode input sensor data for the LLM.
